### ISSUE TITLE
How to change the ip address the gagu listen to?

### ISSUE THREAD

**Issue by wanghaEMQ** [Chisw/gagu#1]
Hi.

There are more than one network interfaces on my server. The gagu was listening to the IP address of the interface en0 by default when started. But for some reason, I need to change the IP address listened to.
So. Is there any way that I could change the IP address the gagu listen to?
It would be better if I could change the IP by just passing the parameter.

Thanks,
wangha.

**Comment by Chisw** [comment]
Hi,

The GAGU service should only be associated with the listening port number.

So, no matter how many IP addresses there are, as long as the corresponding port number is used, the service can be accessed, even though only one IP address is displayed in the terminal when service started.

I'll test this out when I have time and I will try to display all IP addresses after the service started in subsequent versions.

Just try your another IP address with same port, it might work.

If it still doesn't work, remember to reply me again.

😊

**Comment by Chisw** [comment]
@wanghaEMQ

Sorry, I read your description again, I may have misunderstood what you meant just now.

You probably don't want one of the IPs to work, right?

Originally, I had a feature plan about IP black and white lists, but this may not meet your needs. 

I may need to do some more research on this, and it will take some time.

**Comment by wanghaEMQ** [comment]
@Chisw

Good morning.
I am sorry that my description of the issue may not be clear enough.
Yes. There are three network interfaces on my server. Each interface connects to a different network.
For example. The first IP(en0) is `192.168.1.2/16`, the second IP(en1) is `192.168.2.2/16`, and the third IP(en2) is for public.
The GAGU service is only available for devices in `192.168.1.2/16(en0)` when started.

An easy way to make GAGU service available for all devices in those three networks is to listen to `http://0.0.0.0:port`.
But `gagu -h` seems not to give any information about setting the IP listen to.

Thanks.
wangha.

**Comment by Chisw** [comment]
@wanghaEMQ

Good news!

I have to admit that my knowledge in computer networks is really lacking. 

Fortunately, I checked the relevant documents and found this parameter.

Now, you can pass the parameter  in GAGU `v0.0.36` like this:

```sh
gagu -H 0.0.0.0
```

Thanks for your feedback.

**Comment by wanghaEMQ** [comment]
Cool. Thanks a lot!
